### ISSUE TITLE
Amazon order

### ISSUE THREAD

**Issue by apaoli** [LCAS/lincoln_youbot#10]
@marc-hanheide @Jailander @webbam46 @enricodale Router, Webcam and Xtion finally arrived from Amazon!! We can proceed with the real robot :+1:

**Comment by webbam46** [comment]
That's great. Were you going to fix the camera onto the robot for us?

**Comment by marc-hanheide** [comment]
That's was the plan as far as I understood. I think @enricodale volunteered to mount it.

**Comment by webbam46** [comment]
@enricodale http://www.youbot-store.com/wiki/index.php/Microsoft_LifeCam
