### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/lincoln_youbot#3]
- [x] @webbam46 set up his own laptop for simulation
- [x] @apaoli to get @webbam46 a PC to use
- [x] @apaoli to buy Wireless Router
- [x] @apaoli to buy webcam
- [x] @marc-hanheide to help with network setup

**Comment by Jailander** [comment]
Hi, I just saw this I tried the youbot simulation following this: 
http://www.youbot-store.com/wiki/index.php?title=Gazebo_simulation&hmswSSOID=10b4d7be36c130126e02a9c81ce579a7f71c954f

you can find some tutorials here: http://www.youbot-store.com/wiki/index.php/Software under the ROS section

**Comment by marc-hanheide** [comment]
@apaoli @enricodale did you get Wifi router and PC yet?

**Comment by apaoli** [comment]
@marc-hanheide @webbam46 I've just checked and the router and camera haven't been dispatched yet .I guess they will be delivered in this week.
I guess today we can discuss what Adam did during this week. What do you think?

**Comment by apaoli** [comment]
@marc-hanheide @webbam46 I've just checked and the router and camera haven't been dispatched yet .I guess they will be delivered in this week.
I guess today we can discuss what Adam did during this week. What do you think?

**Comment by apaoli** [comment]
Sorry guys, I closed the thread by mistake. I hope is still open now. S

**Comment by marc-hanheide** [comment]
Can @apaoli and @enricodale please mount the web cam as soon as it arrives?
