### ISSUE TITLE
package up circle detector

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/lincoln_youbot#5]
work with Peter and Tom to find a version to be released ASAP

**Comment by Jailander** [comment]
As discussed in gitter the version to be released is at https://github.com/lrse/whycon

Recommended documentation at https://github.com/gestom/whycon/wiki

**Comment by marc-hanheide** [comment]
done! installable via the normal [LCAS/STRANDS repository](https://github.com/strands-project-releases/strands-releases/wiki#using-the-strands-repository), then run
1. `sudo apt-get update`
2. `sudo apt-get install ros-indigo-whycon`
3. read [Wiki](https://github.com/gestom/whycon/wiki/Reference) for details and parameters, and [Tutorial](https://github.com/gestom/whycon/wiki/Tutorial) for usage (interesting for you @webbam46 and @enricodale)

I'll close this as accomplished.

**Comment by marc-hanheide** [comment]
I think @gestom might also want to know.

**Comment by marc-hanheide** [comment]
got too excited too early... the package was missing proper install targets. Maybe https://github.com/LCAS/whycon/pull/2 will fix it. I'll re-open until I see it working.

**Comment by marc-hanheide** [comment]
looks better now
