### ISSUE TITLE
We need a name for this robot

### ISSUE THREAD

**Issue by Jailander** [LCAS/lincoln_youbot#7]
Hi it would make package naming a lot easier to have a name for the robot

**Comment by marc-hanheide** [comment]
How about **PickSie** (_PICK_ing _S_ome _I_tems from the _E_nvironment), but of course it really is inspired by [The Pixies](https://en.wikipedia.org/wiki/Pixies).

**Comment by Jailander** [comment]
Love it! will use it if @apaoli @enricodale @webbam46 approve

**Comment by webbam46** [comment]
Fine with me! Am I meant to know who The Pixies are, or is that a bit before my time?..

**Comment by marc-hanheide** [comment]
The Godfathers or Grunge... kind off

**Comment by apaoli** [comment]
Hi guys! I like PickSie :+1: I definitely approve it!!

**Comment by Jailander** [comment]
PickSie is the chosen name I'll close
